-- [VÔ HIỆU HÓA] Đã loại bỏ bảng citizen, các lệnh này không còn hợp lệ.
-- INSERT INTO report ... FROM citizen c ...
-- [VÔ HIỆU HÓA] Đã loại bỏ bảng citizen, các lệnh này không còn hợp lệ.
-- INSERT INTO report ... FROM citizen c ...
-- [VÔ HIỆU HÓA] Đã loại bỏ bảng citizen, các lệnh này không còn hợp lệ.
-- INSERT INTO report ... FROM citizen c ...
-- [VÔ HIỆU HÓA] Đã loại bỏ bảng citizen, các lệnh này không còn hợp lệ.
-- INSERT INTO reply ... FROM report r ...